#!/usr/bin/env python3
"""The local demo (P9 ``make demo``; REQ-FND-02): one cross-platform entry point for Windows (PowerShell, cmd, Git
Bash), macOS and Linux. Python 3.9+ standard library only; needs Docker (Docker Desktop at 4 GB is enough).

    python infra/demo/demo.py up          # make demo: write throwaway secrets on first run, build, start, seed, banner
    python infra/demo/demo.py down        # make demo-down: stop the demo (its data is kept)
    python infra/demo/demo.py reset --yes # make demo-reset: wipe the demo's volumes only, then start it fresh
    python infra/demo/demo.py totp [ADDRESS]   # make demo-totp: current TOTP codes of the demo logins
    python infra/demo/demo.py logins      # the demo logins and the shared demo password
    python infra/demo/demo.py clock [--days N] [--hours N]  # make demo-clock: show or move the dev/test clock
    python infra/demo/demo.py reminders   # make demo-reminders: send today's reminders now (Mailpit)
    python infra/demo/demo.py stats       # make demo-stats: memory per container (docker stats)
    python infra/demo/demo.py logs        # make demo-logs
    python infra/demo/demo.py e2e-env     # E2E_VERIFY_CERT_ID and E2E_DATABASE_OWNER_URL for Playwright
    python infra/demo/demo.py config      # validate the merged compose file (docker compose config)

Secrets: ``init`` (run by ``up``) writes ``infra/demo/.env`` (database passwords, read by compose) and
``infra/demo/backend.env`` (the app's keys) with random values, once; both are gitignored and never overwritten, and
``backend/.env`` is created from ``backend/.env.example`` when missing, for the LLM variables. Extra compose files
(for example a local CA override that a build machine needs) come from ``DEMO_COMPOSE_EXTRA``, separated by the
platform's path separator; they are never part of the repository.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
INFRA = REPO / "infra"
DEMO_DIR = INFRA / "demo"
COMPOSE_ENV = DEMO_DIR / ".env"
BACKEND_ENV = DEMO_DIR / "backend.env"
BACKEND_DOTENV = REPO / "backend" / ".env"
BACKEND_EXAMPLE = REPO / "backend" / ".env.example"
PROJECT = "bridge-demo"
URLS = (
    ("Web app", "http://localhost:3000"),
    ("Mailpit (every email the demo sends)", "http://localhost:8025"),
    ("API docs", "http://localhost:8000/api/docs"),
)
HEADER = (
    "# Generated by infra/demo/demo.py for the local demo only: throwaway random values, never commit, never reuse.\n"
    "# Deleting this file while the demo's data exists breaks the demo: run make demo-reset to start over.\n"
)


def _hex(nbytes: int) -> str:
    return secrets.token_hex(nbytes)


def _b64(nbytes: int) -> str:
    return base64.b64encode(secrets.token_bytes(nbytes)).decode("ascii")


def compose_env_values() -> dict[str, str]:
    """infra/demo/.env: what docker compose interpolates (the dev stack's database role passwords)."""
    return {
        "POSTGRES_SUPERUSER_PASSWORD": _hex(24),
        "BRIDGE_OWNER_PASSWORD": _hex(24),
        "BRIDGE_APP_PASSWORD": _hex(24),
    }


def backend_env_values() -> dict[str, str]:
    """infra/demo/backend.env: the app's secrets (bridge/config.py; every name is in backend/.env.example)."""
    return {
        "SECRET_KEY": _hex(32),
        "DATA_ENCRYPTION_KEY": _b64(32),
        "RECOVERY_CODE_PEPPER": _hex(32),
        "TIER2_LOCAL_KEK": _b64(32),
        "PROVENANCE_SIGNING_KEY": _b64(32),
    }


def _write_once(path: Path, values: dict[str, str]) -> bool:
    """Write ``values`` to ``path`` unless it exists; True when written."""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    body = HEADER + "".join(f"{name}={value}\n" for name, value in values.items())
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(body)
    return True


def init() -> list[str]:
    """Create the missing local files (never overwrites one); what was created, for the log."""
    created = []
    if _write_once(COMPOSE_ENV, compose_env_values()):
        created.append(str(COMPOSE_ENV.relative_to(REPO)))
    if _write_once(BACKEND_ENV, backend_env_values()):
        created.append(str(BACKEND_ENV.relative_to(REPO)))
    if not BACKEND_DOTENV.exists():
        shutil.copyfile(BACKEND_EXAMPLE, BACKEND_DOTENV)
        created.append(str(BACKEND_DOTENV.relative_to(REPO)))
    return created


def compose_files() -> list[str]:
    files = [str(INFRA / "docker-compose.dev.yml"), str(INFRA / "docker-compose.demo.yml")]
    extra = os.environ.get("DEMO_COMPOSE_EXTRA", "")
    files += [item for item in extra.split(os.pathsep) if item.strip()]
    return files


def compose(*args: str) -> list[str]:
    command = ["docker", "compose", "--env-file", str(COMPOSE_ENV)]
    for file in compose_files():
        command += ["-f", file]
    return [*command, *args]


def run(command: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, check=check, text=True, capture_output=capture, cwd=REPO)  # noqa: S603


def volume_exists(name: str) -> bool:
    return run(["docker", "volume", "inspect", name], check=False, capture=True).returncode == 0


def banner() -> None:
    width = max(len(label) for label, _ in URLS)
    print("\nThe demo is up (make demo-down stops it; make demo-reset wipes its data and starts again).\n")
    for label, url in URLS:
        print(f"  {label:<{width}}  {url}")
    print()
    run(compose("exec", "-T", "api", "python", "-m", "bridge.demo", "logins"), check=False)
    print("Move the app's clock (deadlines): make demo-clock DAYS=3; send today's reminders now: make demo-reminders")


def cmd_up(_: argparse.Namespace) -> int:
    for path in init():
        print(f"demo: created {path} (throwaway local values; gitignored)")
    run(compose("up", "-d", "--build", "--wait"))
    banner()
    return 0


def cmd_down(_: argparse.Namespace) -> int:
    run(compose("down"))
    return 0


def cmd_reset(args: argparse.Namespace) -> int:
    if not args.yes:
        print("reset wipes the demo's database, files and email (the dev stack is not touched).", file=sys.stderr)
        print("Run it by name to confirm: make demo-reset (or demo.py reset --yes).", file=sys.stderr)
        return 2
    init()
    run(compose("down", "--volumes", "--remove-orphans"))
    return cmd_up(args)


def cmd_totp(args: argparse.Namespace) -> int:
    extra = [args.address] if args.address else []
    return run(compose("exec", "-T", "api", "python", "-m", "bridge.demo", "totp", *extra), check=False).returncode


def cmd_clock(args: argparse.Namespace) -> int:
    moves = ["--days", str(args.days), "--hours", str(args.hours)]
    return run(compose("exec", "-T", "api", "python", "-m", "bridge.demo", "clock", *moves), check=False).returncode


def cmd_reminders(_: argparse.Namespace) -> int:
    """One pass of the developer nudge (EM7) and the organisation digest at the shared clock's time, as the worker's
    jobs run them, without waiting for 07:30/08:30 EAT (python -m bridge.reminders refuses production)."""
    command = compose("exec", "-T", "worker", "python", "-m", "bridge.reminders", "run", "--now")
    return run(command, check=False).returncode


def cmd_logins(_: argparse.Namespace) -> int:
    return run(compose("exec", "-T", "api", "python", "-m", "bridge.demo", "logins"), check=False).returncode


def cmd_logs(_: argparse.Namespace) -> int:
    return run(compose("logs", "-f", "--tail=100"), check=False).returncode


def cmd_stats(_: argparse.Namespace) -> int:
    names = run(compose("ps", "--format", "{{.Name}}"), capture=True).stdout.split()
    if not names:
        print("the demo is not running (make demo)", file=sys.stderr)
        return 1
    table = "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}"
    return run(["docker", "stats", "--no-stream", "--format", table, *names], check=False).returncode


def cmd_e2e_env(_: argparse.Namespace) -> int:
    """The Playwright variables for this stack, as NAME=value lines (export them, or put them in the CI env)."""
    found = run(
        compose("exec", "-T", "api", "python", "-m", "bridge.demo", "cert-id", "--wait", "180"), capture=True
    )
    values = dict(line.split("=", 1) for line in COMPOSE_ENV.read_text(encoding="utf-8").splitlines() if "=" in line)
    owner = values["BRIDGE_OWNER_PASSWORD"]
    print(f"E2E_VERIFY_CERT_ID={found.stdout.strip()}")
    print(f"E2E_DATABASE_OWNER_URL=postgresql://bridge_owner:{owner}@127.0.0.1:5432/bridge")
    return 0


def cmd_config(_: argparse.Namespace) -> int:
    for path in init():
        print(f"demo: created {path} (throwaway local values; gitignored)")
    return run(compose("config", "--quiet"), check=False).returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="infra/demo/demo.py", description=__doc__.split("\n\n")[0])
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("up", help="start the demo (first run: secrets, build, seed)").set_defaults(func=cmd_up)
    commands.add_parser("down", help="stop the demo, keeping its data").set_defaults(func=cmd_down)
    reset = commands.add_parser("reset", help="wipe the demo's volumes, then start it fresh")
    reset.add_argument("--yes", action="store_true", help="confirm (make demo-reset passes it)")
    reset.set_defaults(func=cmd_reset)
    totp = commands.add_parser("totp", help="current TOTP codes of the demo logins")
    totp.add_argument("address", nargs="?", help="one demo login: print its code only")
    totp.set_defaults(func=cmd_totp)
    commands.add_parser("logins", help="the demo logins").set_defaults(func=cmd_logins)
    clock = commands.add_parser("clock", help="show the dev/test clock, or move it forward")
    clock.add_argument("--days", type=int, default=0)
    clock.add_argument("--hours", type=int, default=0)
    clock.set_defaults(func=cmd_clock)
    commands.add_parser("reminders", help="send today's reminders now").set_defaults(func=cmd_reminders)
    commands.add_parser("logs", help="follow the demo's logs").set_defaults(func=cmd_logs)
    commands.add_parser("stats", help="memory and CPU per demo container").set_defaults(func=cmd_stats)
    commands.add_parser("e2e-env", help="Playwright variables for this stack").set_defaults(func=cmd_e2e_env)
    commands.add_parser("config", help="validate the merged compose configuration").set_defaults(func=cmd_config)
    args = parser.parse_args(argv)
    try:
        if args.command == "up" and not COMPOSE_ENV.exists() and volume_exists(f"{PROJECT}_pgdata"):
            # The database was initialised with the passwords of a file that is gone: new ones would not open it.
            print("demo: the demo's database exists but infra/demo/.env is gone: run make demo-reset", file=sys.stderr)
            return 2
        code: int = args.func(args)
    except subprocess.CalledProcessError as exc:
        return exc.returncode or 1
    except FileNotFoundError as exc:  # docker is not installed or not on PATH
        print(f"demo: {exc.filename or exc} not found: install Docker Desktop and start it", file=sys.stderr)
        return 127
    return code


if __name__ == "__main__":
    sys.exit(main())
