"""Parity of the ported reminder policy and email with the local companion (REQ-REM-00, AC-REM-4/a groundwork).

Every file in tests/fixtures/reminder_parity/ holds inputs and the outputs reminder/remind.py produced for them
(generated by scripts/gen_reminder_parity_fixtures.py with the legacy venv; scripts/test_reminder_parity_fixtures.py
fails when reminder/ and the committed files disagree). The backend never imports reminder/: this test reads JSON.

The only tolerated difference is the spelling of two escaped characters in the HTML part: Jinja2's autoescape
(markupsafe) writes `&#34;` and `&#39;` where the companion's `html.escape` wrote `&quot;` and `&#x27;`.
"""

from __future__ import annotations

import copy
import json
from collections import Counter
from dataclasses import asdict
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pytest

from bridge.reminders.compose import compose_email, template_notices
from bridge.reminders.policy import (
    GitState,
    Project,
    ReminderConfig,
    Verdict,
    actionable,
    classify,
    fallback_text,
    finished,
    gave_up,
    pending_channels,
    pick_featured,
    record,
)

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "reminder_parity"
KINDS = ("scenario", "record", "pending", "notices")
CHANNELS = ("email", "whatsapp")


def _fixtures(kind: str) -> list[Any]:
    paths = sorted(FIXTURE_DIR.glob(f"{kind}_*.json"))
    return [pytest.param(json.loads(p.read_text(encoding="utf-8")), id=p.stem) for p in paths]


def _project(data: dict[str, Any]) -> Project:
    git = data["git"]
    return Project(**{**data, "git": None if git is None else GitState(**git)})


def legacy_entities(html: str) -> str:
    """The companion's spelling of the two characters markupsafe escapes differently (see the module docstring)."""
    return html.replace("&#34;", "&quot;").replace("&#39;", "&#x27;")


def test_the_fixture_spread_is_complete() -> None:
    kinds = Counter(p.name.split("_", 1)[0] for p in FIXTURE_DIR.glob("*.json"))
    assert set(kinds) == set(KINDS)
    assert sum(kinds.values()) >= 25
    assert all(count >= 5 for count in kinds.values()), kinds


@pytest.mark.parametrize("fixture", _fixtures("scenario"))
def test_scenario_parity(fixture: dict[str, Any]) -> None:
    given, expected = fixture["input"], fixture["expected"]
    projects = [_project(p) for p in given["projects"]]
    cfg = ReminderConfig(**given["config"])
    today = date.fromisoformat(given["today"])
    now: float = given["now"]
    verdicts = {name: Verdict(**v) for name, v in given["verdicts"].items()}

    flagged, quiet, held = classify(projects, cfg, now, today)
    assert {
        "flagged": [{"name": f.name, "cold": f.cold, "risks": f.risks, "headline": f.headline()} for f in flagged],
        "quiet": [p.name for p in quiet],
        "held": [[p.name, why] for p, why in held],
    } == expected["classify"]

    featured = pick_featured(flagged, given["featured_log"])
    assert (featured.name if featured else None) == expected["featured"]
    assert {f.name: asdict(fallback_text(f)) for f in flagged} == expected["fallback"]
    assert [f.name for f in actionable(flagged, verdicts)] == expected["actionable"]

    skipped = [(name, why) for name, why in given["skipped"]]
    subject, text, html = compose_email(flagged, quiet, held, skipped, verdicts, cfg, today, now, given["notices"])
    assert subject == expected["email"]["subject"]
    assert text == expected["email"]["text"]
    assert legacy_entities(html) == expected["email"]["html"]


@pytest.mark.parametrize("fixture", _fixtures("record"))
def test_record_parity(fixture: dict[str, Any]) -> None:
    day = fixture["input"]["day"]
    for call, step in zip(fixture["input"]["calls"], fixture["expected"]["steps"], strict=True):
        day = record(
            day,
            call["channel"],
            ok=call["ok"],
            now=datetime.fromisoformat(call["now"]),
            detail=call["detail"],
            transient=call["transient"],
            force=call["force"],
            status=call["status"],
        )
        assert day == step["day"]
        assert {c: finished(day.get(c)) for c in CHANNELS} == step["finished"]
        assert {c: gave_up(day.get(c)) for c in CHANNELS} == step["gave_up"]


@pytest.mark.parametrize("fixture", _fixtures("record"))
def test_record_never_mutates_its_input(fixture: dict[str, Any]) -> None:
    day = fixture["input"]["day"]
    for call in fixture["input"]["calls"]:
        before = copy.deepcopy(day)
        new = record(
            day,
            call["channel"],
            ok=call["ok"],
            now=datetime.fromisoformat(call["now"]),
            detail=call["detail"],
            transient=call["transient"],
            force=call["force"],
            status=call["status"],
        )
        assert day == before
        day = new


@pytest.mark.parametrize("fixture", _fixtures("pending"))
def test_once_a_day_guard_parity(fixture: dict[str, Any]) -> None:
    given = fixture["input"]
    pending = pending_channels(
        given["day"],
        given["channels"],
        datetime.fromisoformat(given["now"]),
        given["send_after_hour"],
        force=given["force"],
        dry_run=given["dry_run"],
    )
    assert pending == fixture["expected"]["pending"]


@pytest.mark.parametrize("fixture", _fixtures("notices"))
def test_template_notices_parity(fixture: dict[str, Any]) -> None:
    given = fixture["input"]
    assert template_notices(given["state"], date.fromisoformat(given["today"])) == fixture["expected"]["lines"]
